"""initial_schema

Revision ID: ec607a19ed0a
Revises: 
Create Date: 2026-06-02 17:30:59.502670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ec607a19ed0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_occurred', 'audit_trail', ['occurred_at'], unique=False)
    op.create_index('ix_audit_type', 'audit_trail', ['event_type'], unique=False)
    op.create_table('bankroll_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('units_total', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bankroll_recorded_at', 'bankroll_snapshots', ['recorded_at'], unique=False)
    op.create_table('confidence_calibration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=True),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('confidence_bucket', sa.String(length=20), nullable=True),
    sa.Column('predicted_win_rate', sa.Float(), nullable=False),
    sa.Column('actual_win_rate', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport', 'market', 'confidence_bucket')
    )
    op.create_table('daily_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('safe_pick_ids', sa.JSON(), nullable=True),
    sa.Column('medium_pick_ids', sa.JSON(), nullable=True),
    sa.Column('high_pick_ids', sa.JSON(), nullable=True),
    sa.Column('parlay_pick_ids', sa.JSON(), nullable=True),
    sa.Column('total_units', sa.Float(), nullable=True),
    sa.Column('expected_roi', sa.Float(), nullable=True),
    sa.Column('actual_units', sa.Float(), nullable=True),
    sa.Column('actual_roi', sa.Float(), nullable=True),
    sa.Column('settled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('news_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('sport', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('affected_players', sa.JSON(), nullable=True),
    sa.Column('affected_teams', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_fetched', 'news_events', ['fetched_at'], unique=False)
    op.create_index('ix_news_sport', 'news_events', ['sport'], unique=False)
    op.create_table('parlays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('parlay_type', sa.String(length=30), nullable=True),
    sa.Column('combined_odds', sa.Float(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('potential_payout', sa.Float(), nullable=False),
    sa.Column('ev_pct', sa.Float(), nullable=True),
    sa.Column('win_probability', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('legs_won', sa.Integer(), nullable=True),
    sa.Column('pnl_units', sa.Float(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=True),
    sa.Column('dimension_value', sa.String(length=100), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('total_picks', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('units_won', sa.Float(), nullable=True),
    sa.Column('units_lost', sa.Float(), nullable=True),
    sa.Column('roi_pct', sa.Float(), nullable=True),
    sa.Column('avg_clv_pct', sa.Float(), nullable=True),
    sa.Column('avg_ev_pct', sa.Float(), nullable=True),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension', 'dimension_value', 'period', 'period_start')
    )
    op.create_index('ix_perf_dimension', 'performance_metrics', ['dimension', 'dimension_value'], unique=False)
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('bankroll', sa.Float(), nullable=True),
    sa.Column('risk_profile', sa.String(length=20), nullable=True),
    sa.Column('sports', sa.JSON(), nullable=True),
    sa.Column('max_units', sa.Integer(), nullable=True),
    sa.Column('min_ev', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('abbrev', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teams_sport', 'teams', ['sport_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_team', sa.String(length=200), nullable=True),
    sa.Column('away_team', sa.String(length=200), nullable=True),
    sa.Column('commence_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('home_score', sa.Float(), nullable=True),
    sa.Column('away_score', sa.Float(), nullable=True),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('weather_temp', sa.Float(), nullable=True),
    sa.Column('weather_wind', sa.Float(), nullable=True),
    sa.Column('weather_precip', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_games_commence', 'games', ['commence_time'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('injury_detail', sa.Text(), nullable=True),
    sa.Column('injury_updated', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_players_sport', 'players', ['sport_id'], unique=False)
    op.create_index('ix_players_status', 'players', ['status'], unique=False)
    op.create_index('ix_players_team', 'players', ['team_id'], unique=False)
    op.create_table('line_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('selection', sa.String(length=200), nullable=True),
    sa.Column('book', sa.String(length=50), nullable=True),
    sa.Column('odds_before', sa.Integer(), nullable=True),
    sa.Column('odds_after', sa.Integer(), nullable=True),
    sa.Column('implied_before', sa.Float(), nullable=True),
    sa.Column('implied_after', sa.Float(), nullable=True),
    sa.Column('delta_pct', sa.Float(), nullable=True),
    sa.Column('movement_type', sa.String(length=30), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lm_detected', 'line_movements', ['detected_at'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('book', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('selection', sa.String(length=200), nullable=False),
    sa.Column('american_odds', sa.Integer(), nullable=False),
    sa.Column('decimal_odds', sa.Float(), nullable=False),
    sa.Column('implied_prob', sa.Float(), nullable=False),
    sa.Column('line_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_book_market', 'odds_snapshots', ['book', 'market'], unique=False)
    op.create_index('ix_odds_captured_at', 'odds_snapshots', ['captured_at'], unique=False)
    op.create_index('ix_odds_game_market', 'odds_snapshots', ['game_id', 'market'], unique=False)
    op.create_table('picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('selection', sa.String(length=200), nullable=False),
    sa.Column('best_book', sa.String(length=50), nullable=False),
    sa.Column('american_odds_at_gen', sa.Integer(), nullable=False),
    sa.Column('decimal_odds_at_gen', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=10), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('ev_pct', sa.Float(), nullable=False),
    sa.Column('confidence_pct', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('statistical_score', sa.Float(), nullable=True),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('market_score', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('news_impact_score', sa.Float(), nullable=True),
    sa.Column('injury_impact_score', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('key_factors', sa.JSON(), nullable=True),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('american_odds_close', sa.Integer(), nullable=True),
    sa.Column('clv_pct', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('actual_pnl_units', sa.Float(), nullable=True),
    sa.Column('parlay_id', sa.Integer(), nullable=True),
    sa.Column('is_parlay_leg', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['parlay_id'], ['parlays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_picks_generated_at', 'picks', ['generated_at'], unique=False)
    op.create_index('ix_picks_result', 'picks', ['result'], unique=False)
    op.create_index('ix_picks_settlement', 'picks', ['result', 'recommendation', 'generated_at'], unique=False)
    op.create_index('ix_picks_sport', 'picks', ['sport'], unique=False)
    op.create_index('ix_picks_units', 'picks', ['units'], unique=False)
    op.create_table('alert_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=True),
    sa.Column('pick_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(length=100), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pick_id'], ['picks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_sent_at', 'alert_records', ['sent_at'], unique=False)
    op.create_table('clv_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pick_id', sa.Integer(), nullable=True),
    sa.Column('sport', sa.String(length=50), nullable=True),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('book', sa.String(length=50), nullable=True),
    sa.Column('odds_at_pick', sa.Integer(), nullable=False),
    sa.Column('odds_at_close', sa.Integer(), nullable=False),
    sa.Column('implied_at_pick', sa.Float(), nullable=False),
    sa.Column('implied_at_close', sa.Float(), nullable=False),
    sa.Column('clv_pct', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pick_id'], ['picks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pick_id')
    )
    op.create_index('ix_clv_market', 'clv_records', ['market'], unique=False)
    op.create_index('ix_clv_sport', 'clv_records', ['sport'], unique=False)
    op.create_table('model_consensus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pick_id', sa.Integer(), nullable=True),
    sa.Column('statistical_rec', sa.String(length=10), nullable=True),
    sa.Column('ml_rec', sa.String(length=10), nullable=True),
    sa.Column('market_rec', sa.String(length=10), nullable=True),
    sa.Column('trend_rec', sa.String(length=10), nullable=True),
    sa.Column('consensus_pct', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pick_id'], ['picks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pick_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('explanation_rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pick_id'], ['picks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_pick_id', 'user_feedback', ['pick_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_pick_id', table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_table('model_consensus')
    op.drop_index('ix_clv_sport', table_name='clv_records')
    op.drop_index('ix_clv_market', table_name='clv_records')
    op.drop_table('clv_records')
    op.drop_index('ix_alerts_sent_at', table_name='alert_records')
    op.drop_table('alert_records')
    op.drop_index('ix_picks_units', table_name='picks')
    op.drop_index('ix_picks_sport', table_name='picks')
    op.drop_index('ix_picks_settlement', table_name='picks')
    op.drop_index('ix_picks_result', table_name='picks')
    op.drop_index('ix_picks_generated_at', table_name='picks')
    op.drop_table('picks')
    op.drop_index('ix_odds_game_market', table_name='odds_snapshots')
    op.drop_index('ix_odds_captured_at', table_name='odds_snapshots')
    op.drop_index('ix_odds_book_market', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index('ix_lm_detected', table_name='line_movements')
    op.drop_table('line_movements')
    op.drop_index('ix_players_team', table_name='players')
    op.drop_index('ix_players_status', table_name='players')
    op.drop_index('ix_players_sport', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_games_commence', table_name='games')
    op.drop_table('games')
    op.drop_index('ix_teams_sport', table_name='teams')
    op.drop_table('teams')
    op.drop_table('user_profiles')
    op.drop_table('sports')
    op.drop_index('ix_perf_dimension', table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_table('parlays')
    op.drop_index('ix_news_sport', table_name='news_events')
    op.drop_index('ix_news_fetched', table_name='news_events')
    op.drop_table('news_events')
    op.drop_table('daily_portfolios')
    op.drop_table('confidence_calibration')
    op.drop_index('ix_bankroll_recorded_at', table_name='bankroll_snapshots')
    op.drop_table('bankroll_snapshots')
    op.drop_index('ix_audit_type', table_name='audit_trail')
    op.drop_index('ix_audit_occurred', table_name='audit_trail')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
